### PR TITLE
(eclipse branch) Make project compile in Eclipse and using arm-none-eabi-g++

### PR DESCRIPTION
**Pull request by pup05**
Konstantin, thanks for the changes and pull request!  I'm going to merge this into a new branch on pixelmatix/aurora for evaluation before merging it to master.

### CODE REVIEW

**Comment by pup05** [comment]
Good news: compiles without any errors or warning in both Visual Studio (with Visual Micro) and Arduino 1.0.6, and all the patterns and settings seem to work fine.  Not so good news: the Animations (loaded from the SD card) don't work.  Can you confirm this is the case in Eclipse?  Do you have the SD card wired up?  I hope to investigate tonight and try to find the cause.

**Comment by kigster** [comment]
I have not tested animations with Sd card yet :( I'm not sure if they
worked before on the pre-commit point.

On Friday, January 2, 2015, Jason Coon <notifications@github.com> wrote:

> Good news: compiles without any errors or warning in both Visual Studio
> (with Visual Micro) and Arduino 1.0.6, and all the patterns and settings
> seem to work fine. Not so good news: the Animations (loaded from the SD
> card) don't work. Can you confirm this is the case in Eclipse? Do you have
> the SD card wired up? I hope to investigate tonight and try to find the
> cause.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelmatix/aurora/pull/9#issuecomment-68534097>.
>


-- 


*Konstantin Gredeskoul*CTO :: Wanelo Inc
cell: (415) 265 1054

**Comment by kigster** [comment]
I can also wire up SD card later tonight and see if I can make it work with both master branch and this one. To be honest I have not been using the SD card functionality at all, just the patterns on auto play :)

**Comment by pup05** [comment]
OK, animations from the SD card work fine in master, and only require a single line change in GifPlayer.h: https://github.com/pixelmatix/aurora/commit/c2ca7ca6a5abc7e3e0e9804ce6ba0b1e797b8ae4

I'm honestly not sure why this works fine in master and not in the eclipse branch...

**Comment by kigster** [comment]
Oh... I think I know why – that was my bad.

If you look at that file in the PR's diff, I removed the line:
```c++
         int len = readByte();	// Check length
```
I did that because I was getting warnings that ```len``` was unused, but it appears that what was important is that readByte() is called, not that the len is set. 

```diff 
 #if DEBUG == 1
         Serial.println("\nProcessing Graphic Control Extension");
-#endif
         int len = readByte();	// Check length
-#if DEBUG == 1
         if (len != 4) {
             Serial.println("Bad graphic control extension");
         }
 @@ -442,7 +445,7 @@ class GifPlayer{
             backUpStream(1);
             dataBlockSize++;
```

**Comment by pup05** [comment]
Ah, that make sense now, thanks.  My change should take care of the problem and the warning.  It's nice that Eclipse gives warnings like that.  I wish Arduino/Teensyduino and Visual Micro did...

**Comment by kigster** [comment]
Yeah totally – this is the advantage of using a "true" software development IDE, like Eclipse or IntelliJ products (IDEA, CLion, RubyMine, etc). I typically learn and customize a lot of shortcuts, so that I can refactor very easily, like rename methods and variables in place, see method definition from another file in a popup, see docs for the method in a popup, click through to see the implementation inside the library.  

From what I hear VisualMicro gives you much tighter Arduino integration and a possibility of debugging.  Debugging Arduinos is one of the big pain points: I simple can not do it, besides using Serial.print.

**Comment by pup05** [comment]
Visual Studio provides all of that, but it just doesn't seem implemented yet in the VisualMicro plugin.  It's definitely a big step up from the Arduino IDE, though.

**Comment by jasoncoon** [comment]
@kigster , you might try out the 1.4 branch if/when you have a chance.  It's updated for Arduino 1.6/Teensyduino 1.21-beta6, and I think I've fixed all the warnings.

**Comment by kigster** [comment]
Sure I will take it for a spin :)

On Saturday, February 28, 2015, Jason Coon <notifications@github.com> wrote:

> @kigster <https://github.com/kigster> , you might try out the 1.4 branch
> if/when you have a chance. It's updated for Arduino 1.6/Teensyduino
> 1.21-beta6, and I think I've fixed all the warnings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelmatix/aurora/pull/9#issuecomment-76563122>.
>


-- 


*Konstantin Gredeskoul*CTO :: Wanelo Inc
cell: (415) 265 1054

**Comment by kigster** [comment]
Checked out the HEAD and tried to compile in Eclipse, and getting some of the similar errors I got before – basically global variables are used inside .h files, without declaring them as extern above. At least that's what I think it is.

I can try to patch it later today, but in the meantime here is a complete list of errors:

```
../Effects.h:215:48: error: 'XY' was not declared in this scope
../Effects.h:227:48: error: 'XY' was not declared in this scope
../Effects.h:238:29: error: 'XY' was not declared in this scope
../Effects.h:247:65: error: 'XY' was not declared in this scope
../Effects.h:256:29: error: 'XY' was not declared in this scope
../Effects.h:262:29: error: 'XY' was not declared in this scope
../Effects.h:269:29: error: 'XY' was not declared in this scope
../Effects.h:272:29: error: 'XY' was not declared in this scope
../Effects.h:275:29: error: 'XY' was not declared in this scope
../Effects.h:278:29: error: 'XY' was not declared in this scope
../Effects.h:281:29: error: 'XY' was not declared in this scope
../Effects.h:284:29: error: 'XY' was not declared in this scope
../Effects.h:287:29: error: 'XY' was not declared in this scope
../Effects.h:296:33: error: 'XY' was not declared in this scope
../Effects.h:300:33: error: 'XY' was not declared in this scope
../Effects.h:304:33: error: 'XY' was not declared in this scope
../Effects.h:308:33: error: 'XY' was not declared in this scope
../Effects.h:332:49: error: 'XY' was not declared in this scope
../Effects.h:379:29: error: 'XY' was not declared in this scope
../Effects.h:384:25: error: 'XY' was not declared in this scope
../Effects.h:392:29: error: 'XY' was not declared in this scope
../Effects.h:397:25: error: 'XY' was not declared in this scope
../Effects.h:405:29: error: 'XY' was not declared in this scope
../Effects.h:410:25: error: 'XY' was not declared in this scope
../Effects.h:418:29: error: 'XY' was not declared in this scope
../Effects.h:423:41: error: 'XY' was not declared in this scope
../Effects.h:431:29: error: 'XY' was not declared in this scope
../Effects.h:436:41: error: 'XY' was not declared in this scope
../Effects.h:438:40: error: 'XY' was not declared in this scope
../Effects.h:446:33: error: 'XY' was not declared in this scope
../Effects.h:452:41: error: 'XY' was not declared in this scope
../Effects.h:456:40: error: 'XY' was not declared in this scope
../Effects.h:463:29: error: 'XY' was not declared in this scope
../Effects.h:472:29: error: 'XY' was not declared in this scope
../Effects.h:482:49: error: 'XY' was not declared in this scope
../Effects.h:491:33: error: 'XY' was not declared in this scope
../Effects.h:500:33: error: 'XY' was not declared in this scope
../Effects.h:526:27: error: 'XY' was not declared in this scope
../Effects.h:536:21: error: 'XY' was not declared in this scope
../Effects.h:602:28: error: 'XY' was not declared in this scope
../Effects.h:606:28: error: 'XY' was not declared in this scope
../Effects.h:615:31: error: 'XY' was not declared in this scope
../Effects.h:618:31: error: 'XY' was not declared in this scope
../Effects.h:627:58: error: 'XY' was not declared in this scope
../Effects.h:643:62: error: 'XY' was not declared in this scope
../Effects.h:757:23: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:33:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:72:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:75:31: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:95:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:99:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:103:31: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:127:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:132:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:135:34: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:155:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:161:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:163:31: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:182:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:188:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:192:34: error: 'XY' was not declared in this scope
../PatternNoiseSmearing.h:214:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:218:9: error: 'effects' was not declared in this scope
../PatternNoiseSmearing.h:224:37: error: 'XY' was not declared in this scope
../PatternAnalogClock.h:36:9: error: 'effects' was not declared in this scope
../PatternAnalogClock.h:38:9: error: 'clockDisplay' was not declared in this scope
../PatternAnalogClock.h:52:33: error: 'XY' was not declared in this scope
../PatternSwirl.h:53:9: error: 'effects' was not declared in this scope
../PatternSwirl.h:53:29: error: 'XY' was not declared in this scope
../PatternPendulumWave.h:51:9: error: 'effects' was not declared in this scope
../PatternMunch.h:40:37: error: 'XY' was not declared in this scope
../PatternElectricMandala.h:93:37: error: 'XY' was not declared in this scope
../PatternSimplexNoise.h:81:37: error: 'XY' was not declared in this scope
../PatternSnake.h:99:57: error: 'XY' was not declared in this scope
../PatternFire.h:58:33: error: 'XY' was not declared in this scope
../PatternFire.h:64:29: error: 'XY' was not declared in this scope
../PatternFire.h:71:49: error: 'XY' was not declared in this scope
../PatternFire.h:77:33: error: 'XY' was not declared in this scope
../PatternLife.h:84:37: error: 'XY' was not declared in this scope
../PatternSpark.h:70:41: error: 'XY' was not declared in this scope
../PatternEffects.h:58:51: error: 'XY' was not declared in this scope
../PatternEffects.h:89:29: error: 'XY' was not declared in this scope
../Menu.h:99:50: error: 'autoPlayDurationSeconds' was not declared in this scope
../Menu.h:128:54: error: 'autoPlayDurationSeconds' was not declared in this scope
../Menu.h:139:54: error: 'autoPlayDurationSeconds' was not declared in this scope
../Menu.h:218:54: error: 'autoPlayDurationSeconds' was not declared in this scope
../Menu.h:280:54: error: 'autoPlayDurationSeconds' was not declared in this scope
../Menu.h:334:39: error: 'menuColor' was not declared in this scope
../Menu.h:350:39: error: 'menuColor' was not declared in this scope
../Menu.h:359:39: error: 'menuColor' was not declared in this scope
../Menu.h:383:39: error: 'menuColor' was not declared in this scope
../SettingsMenuColor.h:50:31: error: 'menuColor' was not declared in this scope
../SettingsMenuColor.h:115:13: error: 'menuColor' was not declared in this scope
../SettingsMenuColor.h:182:9: error: 'menuColor' was not declared in this scope
../SettingsMenuColor.h:183:23: error: 'saveMenuColor' was not declared in this scope
../SettingsAutoplayDuration.h:37:33: error: 'autoPlayDurationSeconds' was not declared in this scope
../SettingsAutoplayDuration.h:76:9: error: 'autoPlayDurationSeconds' was not declared in this scope
```

**Comment by jasoncoon** [comment]
Yeah, sorry, I fixed all the warnings in Arduino and Visual Studio, but I still don't have Eclipse set up to test with.

**Comment by kigster** [comment]
Sorry I've been super busy.   All errors are about global variables defined elsewhere, used in various header files. To fix this, add "extern variable;" at the top of the header file.  That should make everything compile in eclipse, and I'll verify

**Pull request merged**
